package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Aspectosocial generated by hbm2java
 */
public class Aspectosocial implements java.io.Serializable {

	private int idAspectoSocial;
	private Proyecto proyecto;
	private Integer poblacionTotal;
	private Float hogaresProm;
	private Integer nroViviendas;
	private Integer pblMasculina;
	private Integer pblFemenina;
	private Integer pblAreaurbanaM2;

	public Aspectosocial() {
	}

	public Aspectosocial(int idAspectoSocial, Proyecto proyecto) {
		this.idAspectoSocial = idAspectoSocial;
		this.proyecto = proyecto;
	}

	public Aspectosocial(int idAspectoSocial, Proyecto proyecto, Integer poblacionTotal, Float hogaresProm,
			Integer nroViviendas, Integer pblMasculina, Integer pblFemenina, Integer pblAreaurbanaM2) {
		this.idAspectoSocial = idAspectoSocial;
		this.proyecto = proyecto;
		this.poblacionTotal = poblacionTotal;
		this.hogaresProm = hogaresProm;
		this.nroViviendas = nroViviendas;
		this.pblMasculina = pblMasculina;
		this.pblFemenina = pblFemenina;
		this.pblAreaurbanaM2 = pblAreaurbanaM2;
	}

	public int getIdAspectoSocial() {
		return this.idAspectoSocial;
	}

	public void setIdAspectoSocial(int idAspectoSocial) {
		this.idAspectoSocial = idAspectoSocial;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Integer getPoblacionTotal() {
		return this.poblacionTotal;
	}

	public void setPoblacionTotal(Integer poblacionTotal) {
		this.poblacionTotal = poblacionTotal;
	}

	public Float getHogaresProm() {
		return this.hogaresProm;
	}

	public void setHogaresProm(Float hogaresProm) {
		this.hogaresProm = hogaresProm;
	}

	public Integer getNroViviendas() {
		return this.nroViviendas;
	}

	public void setNroViviendas(Integer nroViviendas) {
		this.nroViviendas = nroViviendas;
	}

	public Integer getPblMasculina() {
		return this.pblMasculina;
	}

	public void setPblMasculina(Integer pblMasculina) {
		this.pblMasculina = pblMasculina;
	}

	public Integer getPblFemenina() {
		return this.pblFemenina;
	}

	public void setPblFemenina(Integer pblFemenina) {
		this.pblFemenina = pblFemenina;
	}

	public Integer getPblAreaurbanaM2() {
		return this.pblAreaurbanaM2;
	}

	public void setPblAreaurbanaM2(Integer pblAreaurbanaM2) {
		this.pblAreaurbanaM2 = pblAreaurbanaM2;
	}

}
