package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Biologia generated by hbm2java
 */
public class Biologia implements java.io.Serializable {

	private int idBiologia;
	private Proyecto proyecto;
	private Long caudalEcologico;
	private Integer areasProtegidas;
	private Integer ecosistemasFragiles;

	public Biologia() {
	}

	public Biologia(int idBiologia, Proyecto proyecto) {
		this.idBiologia = idBiologia;
		this.proyecto = proyecto;
	}

	public Biologia(int idBiologia, Proyecto proyecto, Long caudalEcologico, Integer areasProtegidas,
			Integer ecosistemasFragiles) {
		this.idBiologia = idBiologia;
		this.proyecto = proyecto;
		this.caudalEcologico = caudalEcologico;
		this.areasProtegidas = areasProtegidas;
		this.ecosistemasFragiles = ecosistemasFragiles;
	}

	public int getIdBiologia() {
		return this.idBiologia;
	}

	public void setIdBiologia(int idBiologia) {
		this.idBiologia = idBiologia;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Long getCaudalEcologico() {
		return this.caudalEcologico;
	}

	public void setCaudalEcologico(Long caudalEcologico) {
		this.caudalEcologico = caudalEcologico;
	}

	public Integer getAreasProtegidas() {
		return this.areasProtegidas;
	}

	public void setAreasProtegidas(Integer areasProtegidas) {
		this.areasProtegidas = areasProtegidas;
	}

	public Integer getEcosistemasFragiles() {
		return this.ecosistemasFragiles;
	}

	public void setEcosistemasFragiles(Integer ecosistemasFragiles) {
		this.ecosistemasFragiles = ecosistemasFragiles;
	}

}
