package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

	private Integer idEmpresa;
	private String nombre;
	private String direccion;
	private String region;
	private String provincia;
	private String distrito;
	private String telefono;
	private String fax;
	private String email;
	private String ruc;
	private Set responsables = new HashSet(0);

	public Empresa() {
	}

	public Empresa(String ruc) {
		this.ruc = ruc;
	}

	public Empresa(String nombre, String direccion, String region, String provincia, String distrito, String telefono,
			String fax, String email, String ruc, Set responsables) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.region = region;
		this.provincia = provincia;
		this.distrito = distrito;
		this.telefono = telefono;
		this.fax = fax;
		this.email = email;
		this.ruc = ruc;
		this.responsables = responsables;
	}

	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	public Set getResponsables() {
		return this.responsables;
	}

	public void setResponsables(Set responsables) {
		this.responsables = responsables;
	}

}
