package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Hidrografia generated by hbm2java
 */
public class Hidrografia implements java.io.Serializable {

	private int idHidrografia;
	private Proyecto proyecto;
	private Double caudalRioMasProx;
	private Double caudalCuencaInfl;
	private String rioPrincipal;

	public Hidrografia() {
	}

	public Hidrografia(int idHidrografia, Proyecto proyecto) {
		this.idHidrografia = idHidrografia;
		this.proyecto = proyecto;
	}

	public Hidrografia(int idHidrografia, Proyecto proyecto, Double caudalRioMasProx, Double caudalCuencaInfl,
			String rioPrincipal) {
		this.idHidrografia = idHidrografia;
		this.proyecto = proyecto;
		this.caudalRioMasProx = caudalRioMasProx;
		this.caudalCuencaInfl = caudalCuencaInfl;
		this.rioPrincipal = rioPrincipal;
	}

	public int getIdHidrografia() {
		return this.idHidrografia;
	}

	public void setIdHidrografia(int idHidrografia) {
		this.idHidrografia = idHidrografia;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Double getCaudalRioMasProx() {
		return this.caudalRioMasProx;
	}

	public void setCaudalRioMasProx(Double caudalRioMasProx) {
		this.caudalRioMasProx = caudalRioMasProx;
	}

	public Double getCaudalCuencaInfl() {
		return this.caudalCuencaInfl;
	}

	public void setCaudalCuencaInfl(Double caudalCuencaInfl) {
		this.caudalCuencaInfl = caudalCuencaInfl;
	}

	public String getRioPrincipal() {
		return this.rioPrincipal;
	}

	public void setRioPrincipal(String rioPrincipal) {
		this.rioPrincipal = rioPrincipal;
	}

}
