package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Impacto generated by hbm2java
 */
public class Impacto implements java.io.Serializable {

	private int idImpacto;
	private String tipo;
	private String factor;
	private Integer nivel;
	private String descripcion;
	private Set proyectoimpactos = new HashSet(0);

	public Impacto() {
	}

	public Impacto(int idImpacto) {
		this.idImpacto = idImpacto;
	}

	public Impacto(int idImpacto, String tipo, String factor, Integer nivel, String descripcion, Set proyectoimpactos) {
		this.idImpacto = idImpacto;
		this.tipo = tipo;
		this.factor = factor;
		this.nivel = nivel;
		this.descripcion = descripcion;
		this.proyectoimpactos = proyectoimpactos;
	}

	public int getIdImpacto() {
		return this.idImpacto;
	}

	public void setIdImpacto(int idImpacto) {
		this.idImpacto = idImpacto;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getFactor() {
		return this.factor;
	}

	public void setFactor(String factor) {
		this.factor = factor;
	}

	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProyectoimpactos() {
		return this.proyectoimpactos;
	}

	public void setProyectoimpactos(Set proyectoimpactos) {
		this.proyectoimpactos = proyectoimpactos;
	}

}
