package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Mecanismopartciudadana generated by hbm2java
 */
public class Mecanismopartciudadana implements java.io.Serializable {

	private int idMecanismoPartCiudadana;
	private String mecanismo;
	private String descripcion;
	private String frecuencia;
	private Set mecanismoproyectos = new HashSet(0);

	public Mecanismopartciudadana() {
	}

	public Mecanismopartciudadana(int idMecanismoPartCiudadana) {
		this.idMecanismoPartCiudadana = idMecanismoPartCiudadana;
	}

	public Mecanismopartciudadana(int idMecanismoPartCiudadana, String mecanismo, String descripcion, String frecuencia,
			Set mecanismoproyectos) {
		this.idMecanismoPartCiudadana = idMecanismoPartCiudadana;
		this.mecanismo = mecanismo;
		this.descripcion = descripcion;
		this.frecuencia = frecuencia;
		this.mecanismoproyectos = mecanismoproyectos;
	}

	public int getIdMecanismoPartCiudadana() {
		return this.idMecanismoPartCiudadana;
	}

	public void setIdMecanismoPartCiudadana(int idMecanismoPartCiudadana) {
		this.idMecanismoPartCiudadana = idMecanismoPartCiudadana;
	}

	public String getMecanismo() {
		return this.mecanismo;
	}

	public void setMecanismo(String mecanismo) {
		this.mecanismo = mecanismo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getFrecuencia() {
		return this.frecuencia;
	}

	public void setFrecuencia(String frecuencia) {
		this.frecuencia = frecuencia;
	}

	public Set getMecanismoproyectos() {
		return this.mecanismoproyectos;
	}

	public void setMecanismoproyectos(Set mecanismoproyectos) {
		this.mecanismoproyectos = mecanismoproyectos;
	}

}
