package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Mecanismoproyecto generated by hbm2java
 */
public class Mecanismoproyecto implements java.io.Serializable {

	private MecanismoproyectoId id;
	private Mecanismopartciudadana mecanismopartciudadana;
	private Proyecto proyecto;

	public Mecanismoproyecto() {
	}

	public Mecanismoproyecto(MecanismoproyectoId id, Mecanismopartciudadana mecanismopartciudadana, Proyecto proyecto) {
		this.id = id;
		this.mecanismopartciudadana = mecanismopartciudadana;
		this.proyecto = proyecto;
	}

	public MecanismoproyectoId getId() {
		return this.id;
	}

	public void setId(MecanismoproyectoId id) {
		this.id = id;
	}

	public Mecanismopartciudadana getMecanismopartciudadana() {
		return this.mecanismopartciudadana;
	}

	public void setMecanismopartciudadana(Mecanismopartciudadana mecanismopartciudadana) {
		this.mecanismopartciudadana = mecanismopartciudadana;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

}
