package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

/**
 * MecanismoproyectoId generated by hbm2java
 */
public class MecanismoproyectoId implements java.io.Serializable {

	private int proyectoIdProyecto;
	private int mecanismoPartCiudadanaIdMecanismoPartCiudadana;

	public MecanismoproyectoId() {
	}

	public MecanismoproyectoId(int proyectoIdProyecto, int mecanismoPartCiudadanaIdMecanismoPartCiudadana) {
		this.proyectoIdProyecto = proyectoIdProyecto;
		this.mecanismoPartCiudadanaIdMecanismoPartCiudadana = mecanismoPartCiudadanaIdMecanismoPartCiudadana;
	}

	public int getProyectoIdProyecto() {
		return this.proyectoIdProyecto;
	}

	public void setProyectoIdProyecto(int proyectoIdProyecto) {
		this.proyectoIdProyecto = proyectoIdProyecto;
	}

	public int getMecanismoPartCiudadanaIdMecanismoPartCiudadana() {
		return this.mecanismoPartCiudadanaIdMecanismoPartCiudadana;
	}

	public void setMecanismoPartCiudadanaIdMecanismoPartCiudadana(int mecanismoPartCiudadanaIdMecanismoPartCiudadana) {
		this.mecanismoPartCiudadanaIdMecanismoPartCiudadana = mecanismoPartCiudadanaIdMecanismoPartCiudadana;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MecanismoproyectoId))
			return false;
		MecanismoproyectoId castOther = (MecanismoproyectoId) other;

		return (this.getProyectoIdProyecto() == castOther.getProyectoIdProyecto())
				&& (this.getMecanismoPartCiudadanaIdMecanismoPartCiudadana() == castOther
						.getMecanismoPartCiudadanaIdMecanismoPartCiudadana());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProyectoIdProyecto();
		result = 37 * result + this.getMecanismoPartCiudadanaIdMecanismoPartCiudadana();
		return result;
	}

}
