package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

/**
 * ProyectoId generated by hbm2java
 */
public class ProyectoId implements java.io.Serializable {

	private int idProyecto;
	private int empresaIdEmpresa;

	public ProyectoId() {
	}

	public ProyectoId(int idProyecto, int empresaIdEmpresa) {
		this.idProyecto = idProyecto;
		this.empresaIdEmpresa = empresaIdEmpresa;
	}

	public int getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(int idProyecto) {
		this.idProyecto = idProyecto;
	}

	public int getEmpresaIdEmpresa() {
		return this.empresaIdEmpresa;
	}

	public void setEmpresaIdEmpresa(int empresaIdEmpresa) {
		this.empresaIdEmpresa = empresaIdEmpresa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProyectoId))
			return false;
		ProyectoId castOther = (ProyectoId) other;

		return (this.getIdProyecto() == castOther.getIdProyecto())
				&& (this.getEmpresaIdEmpresa() == castOther.getEmpresaIdEmpresa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProyecto();
		result = 37 * result + this.getEmpresaIdEmpresa();
		return result;
	}

}
