package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Proyectoimpacto generated by hbm2java
 */
public class Proyectoimpacto implements java.io.Serializable {

	private ProyectoimpactoId id;
	private Impacto impacto;
	private Proyecto proyecto;

	public Proyectoimpacto() {
	}

	public Proyectoimpacto(ProyectoimpactoId id, Impacto impacto, Proyecto proyecto) {
		this.id = id;
		this.impacto = impacto;
		this.proyecto = proyecto;
	}

	public ProyectoimpactoId getId() {
		return this.id;
	}

	public void setId(ProyectoimpactoId id) {
		this.id = id;
	}

	public Impacto getImpacto() {
		return this.impacto;
	}

	public void setImpacto(Impacto impacto) {
		this.impacto = impacto;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

}
