package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private ProyectoId id;
	private String nombre;
	private String tipoActividad;
	private String metodo;
	private Double inversionEstimada;
	private String objetivo;
	private Set hidrografias = new HashSet(0);
	private Set aspectosocials = new HashSet(0);
	private Set mecanismoproyectos = new HashSet(0);
	private Set proyectoimpactos = new HashSet(0);
	private Set ubicaciongeograficas = new HashSet(0);
	private Set calidadelementoses = new HashSet(0);
	private Set geomorfologias = new HashSet(0);
	private Set biologias = new HashSet(0);
	private Set meteorologias = new HashSet(0);

	public Proyecto() {
	}

	public Proyecto(ProyectoId id) {
		this.id = id;
	}

	public Proyecto(ProyectoId id, String nombre, String tipoActividad, String metodo, Double inversionEstimada,
			String objetivo, Set hidrografias, Set aspectosocials, Set mecanismoproyectos, Set proyectoimpactos,
			Set ubicaciongeograficas, Set calidadelementoses, Set geomorfologias, Set biologias, Set meteorologias) {
		this.id = id;
		this.nombre = nombre;
		this.tipoActividad = tipoActividad;
		this.metodo = metodo;
		this.inversionEstimada = inversionEstimada;
		this.objetivo = objetivo;
		this.hidrografias = hidrografias;
		this.aspectosocials = aspectosocials;
		this.mecanismoproyectos = mecanismoproyectos;
		this.proyectoimpactos = proyectoimpactos;
		this.ubicaciongeograficas = ubicaciongeograficas;
		this.calidadelementoses = calidadelementoses;
		this.geomorfologias = geomorfologias;
		this.biologias = biologias;
		this.meteorologias = meteorologias;
	}

	public ProyectoId getId() {
		return this.id;
	}

	public void setId(ProyectoId id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipoActividad() {
		return this.tipoActividad;
	}

	public void setTipoActividad(String tipoActividad) {
		this.tipoActividad = tipoActividad;
	}

	public String getMetodo() {
		return this.metodo;
	}

	public void setMetodo(String metodo) {
		this.metodo = metodo;
	}

	public Double getInversionEstimada() {
		return this.inversionEstimada;
	}

	public void setInversionEstimada(Double inversionEstimada) {
		this.inversionEstimada = inversionEstimada;
	}

	public String getObjetivo() {
		return this.objetivo;
	}

	public void setObjetivo(String objetivo) {
		this.objetivo = objetivo;
	}

	public Set getHidrografias() {
		return this.hidrografias;
	}

	public void setHidrografias(Set hidrografias) {
		this.hidrografias = hidrografias;
	}

	public Set getAspectosocials() {
		return this.aspectosocials;
	}

	public void setAspectosocials(Set aspectosocials) {
		this.aspectosocials = aspectosocials;
	}

	public Set getMecanismoproyectos() {
		return this.mecanismoproyectos;
	}

	public void setMecanismoproyectos(Set mecanismoproyectos) {
		this.mecanismoproyectos = mecanismoproyectos;
	}

	public Set getProyectoimpactos() {
		return this.proyectoimpactos;
	}

	public void setProyectoimpactos(Set proyectoimpactos) {
		this.proyectoimpactos = proyectoimpactos;
	}

	public Set getUbicaciongeograficas() {
		return this.ubicaciongeograficas;
	}

	public void setUbicaciongeograficas(Set ubicaciongeograficas) {
		this.ubicaciongeograficas = ubicaciongeograficas;
	}

	public Set getCalidadelementoses() {
		return this.calidadelementoses;
	}

	public void setCalidadelementoses(Set calidadelementoses) {
		this.calidadelementoses = calidadelementoses;
	}

	public Set getGeomorfologias() {
		return this.geomorfologias;
	}

	public void setGeomorfologias(Set geomorfologias) {
		this.geomorfologias = geomorfologias;
	}

	public Set getBiologias() {
		return this.biologias;
	}

	public void setBiologias(Set biologias) {
		this.biologias = biologias;
	}

	public Set getMeteorologias() {
		return this.meteorologias;
	}

	public void setMeteorologias(Set meteorologias) {
		this.meteorologias = meteorologias;
	}

}
