package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

/**
 * ProyectoimpactoId generated by hbm2java
 */
public class ProyectoimpactoId implements java.io.Serializable {

	private int impactoIdImpacto;
	private int proyectoIdProyecto;

	public ProyectoimpactoId() {
	}

	public ProyectoimpactoId(int impactoIdImpacto, int proyectoIdProyecto) {
		this.impactoIdImpacto = impactoIdImpacto;
		this.proyectoIdProyecto = proyectoIdProyecto;
	}

	public int getImpactoIdImpacto() {
		return this.impactoIdImpacto;
	}

	public void setImpactoIdImpacto(int impactoIdImpacto) {
		this.impactoIdImpacto = impactoIdImpacto;
	}

	public int getProyectoIdProyecto() {
		return this.proyectoIdProyecto;
	}

	public void setProyectoIdProyecto(int proyectoIdProyecto) {
		this.proyectoIdProyecto = proyectoIdProyecto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProyectoimpactoId))
			return false;
		ProyectoimpactoId castOther = (ProyectoimpactoId) other;

		return (this.getImpactoIdImpacto() == castOther.getImpactoIdImpacto())
				&& (this.getProyectoIdProyecto() == castOther.getProyectoIdProyecto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getImpactoIdImpacto();
		result = 37 * result + this.getProyectoIdProyecto();
		return result;
	}

}
