package com.bcb.ambienta.ambientaapp.model;
// Generated 16/10/2016 09:54:50 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Ubicaciongeografica generated by hbm2java
 */
public class Ubicaciongeografica implements java.io.Serializable {

	private int idUbicacionGeografica;
	private Proyecto proyecto;
	private Double areaProyHa;
	private Float coordEste;
	private Float coordNorte;

	public Ubicaciongeografica() {
	}

	public Ubicaciongeografica(int idUbicacionGeografica, Proyecto proyecto) {
		this.idUbicacionGeografica = idUbicacionGeografica;
		this.proyecto = proyecto;
	}

	public Ubicaciongeografica(int idUbicacionGeografica, Proyecto proyecto, Double areaProyHa, Float coordEste,
			Float coordNorte) {
		this.idUbicacionGeografica = idUbicacionGeografica;
		this.proyecto = proyecto;
		this.areaProyHa = areaProyHa;
		this.coordEste = coordEste;
		this.coordNorte = coordNorte;
	}

	public int getIdUbicacionGeografica() {
		return this.idUbicacionGeografica;
	}

	public void setIdUbicacionGeografica(int idUbicacionGeografica) {
		this.idUbicacionGeografica = idUbicacionGeografica;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Double getAreaProyHa() {
		return this.areaProyHa;
	}

	public void setAreaProyHa(Double areaProyHa) {
		this.areaProyHa = areaProyHa;
	}

	public Float getCoordEste() {
		return this.coordEste;
	}

	public void setCoordEste(Float coordEste) {
		this.coordEste = coordEste;
	}

	public Float getCoordNorte() {
		return this.coordNorte;
	}

	public void setCoordNorte(Float coordNorte) {
		this.coordNorte = coordNorte;
	}

}
